// let sum = (x, y) => x + y
// console.log(sum(4, 5))

//导入js
// import './2-3-解构赋值'
// import './2-4-数组的遍历方式'
// import './2-5-数组的扩展'
// import './2-6-函数参数'
// import './2-7-扩展运算符与rest参数'
// import './2-8-箭头函数'
// import './2-9-对象的扩展'
// import './2-10-深拷贝与浅拷贝'

// import  './3-1-ES5中的类与继承'
// import  './3-2-ES6中的类与继承'
// import  './3-3-Symbol'
// import './3-4-Set'
// import './3-5-Map'
// import './3-6-字符串的扩展'
// import './3-7- 正则表达式的扩展'
// import './3-8-数值的扩展'
// import './3-9-Proxy'
// import './3-10-反射Reflect'

// import './4-1-异步操作必备知识'
// import './4-2-Ajax原理与Callback Hel'
// import './4-3-promise'
// import './4-4-Promise的静态方法'
// import './4-5-异步编程解决方案Generator'
// import './4-6-迭代器Iterator'
// import './4-7- 模块化Module'

// import './5-1-数组扩展：Array.prototype.includes()'
// import './5-2-数值扩展：幂运算符'

// import './6-1-异步编程解决方案Async Await'
// import './6-2-对象扩展：Object.values()，Object.entries()  1.'
// import './6-3-对象属性描述：Object.getOwnPropertyDescriptors()'
// import './6-4-字符串扩展：String.prototype.padStart()，String.prototype.padEnd()'
// import './6-5 尾逗号Trailing commas'

// import './7-1 异步迭代：for await of'
// import './7-2 正则表达式扩展：dotAll，具名组匹配，后行断言'
// import './7-3 对象扩展：Rest & Spread'
// import './7-4 Promise扩展：Promise.prototype.finally()'
// import './7-5 字符串扩展：放松模板字符串文字限制'

// import './8-1 对象扩展：Object.fromEntries()'
// import './8-2 字符串扩展：String.prototype.trimStart() ，String.prototype.trimEnd()'
// import './8-3 数组扩展：Array.prototype.flat()，Array.prototype.flatMap()'
// import './8-4 修订Function.prototype.toString()'
// import './8-5 可选的Catch Binding'
// import './8-6 JSON扩展：JSON superset，JSON.stringify()增强能力'
// import './8-7 Symbol扩展：Symbol.prototype.description'

// import './9-1 全局模式捕获：String.prototype.matchAll()'
// import './9-2 动态导入：Dynamic import()'
// import './9-3 新的原始数据类型：BigInt'
// import './9-4 Promise扩展：Promise.allSettled()'
// import './9-5 全局对象：globalThis'
// import './9-6 可选链：Optional chaining'
import './9-7 空值合并运算符：Nullish coalescing Operator'